name: TypeScript CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Generate Prisma Module
        run: pnpm install

      - name: Install dependencies
        run: pnpm prisma generate

      - name: Build
        run: pnpm run build
